modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/GeOre/issues"
license="MIT"

[[mods]]
modId="geore"
version="${file.jarVersion}"
displayName="GeOre"
displayURL="https://www.curseforge.com/minecraft/mc-mods/geore"
logoFile="logo.png"
authors="ShyNieke, Mrbysco"
description='''
This mod takes heavy inspiration of the vanilla amethyst geode feature and applies it to other valuables to.
'''

[[dependencies.geore]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.geore]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.2.59-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "geore.mixins.json"